# Input/Output with Pandas

Pandas provides support for reading/writing data from/to varieties of sources. 

#### CSV File

 - reader: **read_csv**
 - writer: **to_csv**

#### MS Excel

 - reader: **read_excel**
 - writer: **to_excel**

#### JSON File

 - reader: **read_json**
 - writer: **to_json**

#### HTML

 - reader: **read_html**
 - writer: **to_html**

#### XML

 - reader: **read_xml**
 - writer: **to_xml**

In [1]:
import numpy as np 
import pandas as pd

#### Reading and Writing CSV Files

In [2]:
house_rent_df = pd.read_csv('./data/source/insurance.csv')
house_rent_df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [3]:
# Get the csv file with header is None.
house_rent_df = pd.read_csv('./data/source/insurance.csv', header = None)
house_rent_df.head()

     0       1       2         3       4          5            6
0  age     sex     bmi  children  smoker     region      charges
1   19  female    27.9         0     yes  southwest    16884.924
2   18    male   33.77         1      no  southeast    1725.5523
3   28    male      33         3      no  southeast     4449.462
4   33    male  22.705         0      no  northwest  21984.47061

In [5]:
# Skip rows
house_rent_df = pd.read_csv('./data/source/insurance.csv', skiprows = 2, header=None)
house_rent_df.head()

    0       1       2  3   4          5            6
0  18    male  33.770  1  no  southeast   1725.55230
1  28    male  33.000  3  no  southeast   4449.46200
2  33    male  22.705  0  no  northwest  21984.47061
3  32    male  28.880  0  no  northwest   3866.85520
4  31  female  25.740  0  no  southeast   3756.62160

In [19]:
# Random number generator.
rng = np.random.default_rng(seed = 100)

# Generating Data of students in the class of 10 students
students = [f's{idx}' for idx in range(1, 11)]
heights = pd.Series(170.0 + 25.0 * rng.standard_normal(10), index = students, name = 'Student_Height')
# print(f'Stident Heights:\n{heights}')

weights = pd.Series(75.0 + 12.0 * rng.standard_normal(10), index = students, name = 'Student_Weight')
# print(f'\nStudent Weight:\n{weights}')

# Genrating student dataframe.
std_df = pd.DataFrame({
    'Student_Height': heights,
    'Student_Weight': weights
}, index=students)

print(f'\nStudent Data:\n{std_df}')

# Writing student data into students_data1.csv
file = './data/target/students_data1.csv'
std_df.to_csv(file)

Student Data:
     Student_Height  Student_Weight
s1       141.061259      101.915669
s2       177.243895       67.662083
s3       189.521352       75.566534
s4       183.599341       96.050816
s5       145.965434       58.944242
s6       196.775217       78.906894
s7       187.536392       66.730587
s8       187.624336       74.762138
s9       188.626565       80.697039
s10      197.608681       51.826783

In [20]:
# Writing student data into students_data2.csv with no index
file = './data/target/students_data2.csv'
std_df.to_csv(file, index=False)

#### Reading and Writing MS Excel File.

In [29]:
# Reading the MS Excel Data.
src_file = './data/source/House_Rent.xlsx'
rental_data = pd.read_excel(src_file, sheet_name='House_Rent_Data')
print(f'All the Data Columns:\n {rental_data.columns}')

# Get only required columns.
house_rent_df = rental_data[['RegionName', 'State', 'Metro', 'CountyName', 'SizeRank', 
                             '2019-10', '2019-11', '2019-12']]

house_rent_df.head()

All the Data Columns:
 Index(['Unnamed: 0', 'RegionName', 'State', 'Metro', 'CountyName', 'SizeRank',
       '2010-02', '2010-03', '2010-04', '2010-05',
       ...
       '2019-03', '2019-04', '2019-05', '2019-06', '2019-07', '2019-08',
       '2019-09', '2019-10', '2019-11', '2019-12'],
      dtype='object', length=125)

,RegionName,State,Metro,CountyName,SizeRank,2019-10,2019-11,2019-12
0,New York,NY,New York-Newark-Jersey City,Queens County,1,2650.0,2600.0,2600.0
1,Los Angeles,CA,Los Angeles-Long Beach-Anaheim,Los Angeles County,2,3000.0,2985.0,2995.0
2,Houston,TX,Houston-The Woodlands-Sugar Land,Harris County,3,1495.0,1471.0,1480.0
3,Chicago,IL,Chicago-Naperville-Elgin,Cook County,4,1750.0,1730.0,1700.0
4,San Antonio,TX,San Antonio-New Braunfels,Bexar County,5,1234.0,1227.0,1208.0

In [31]:
# Saving the house rent data into target file.
tgt_file = './data/target/House_Rent_2029.xlsx'
with pd.ExcelWriter(tgt_file) as writer:
    house_rent_df.to_excel(writer, sheet_name='2029_House_Rent_Data')

#### Reading and Writing JSON File.

In [32]:
books = [
    {'Name': 'The Spy', 'Author': 'Paulo Coelho', 'Price': 3.23},
    {'Name': 'The Perfect Us', 'Author': 'Durjoy Dutta', 'Price': 5.34},
    {'Name': 'Origin', 'Author': 'Dan Brown', 'Price': 7.33},
    {'Name': 'Sapience', 'Author': 'Yuval Noah Harari', 'Price': 9.23},
    {'Name': 'The Last Mughal', 'Author': 'William Dalrymple', 'Price': 13.43},
]

book_df = pd.DataFrame(books)
book_df

              Name             Author  Price
0          The Spy       Paulo Coelho   3.23
1   The Perfect Us       Durjoy Dutta   5.34
2           Origin          Dan Brown   7.33
3         Sapience  Yuval Noah Harari   9.23
4  The Last Mughal  William Dalrymple  13.43

In [ ]:
# Writing to a JSON File. orient - records.
JSONfile = './data/target/Book_Record.json'
book_df.to_json(JSONfile, orient='records')

In [ ]:
# Writing to a JSON File. orient - split.
JSONfile = './data/target/Book_Split.json'
book_df.to_json(JSONfile, orient='split')

In [37]:
# Writing to a JSON File. orient - index.
JSONfile = './data/target/Book_Index.json'
book_df.to_json(JSONfile, orient='index')

In [38]:
# Writing to a JSON File. orient - columns.
JSONfile = './data/target/Book_Columns.json'
book_df.to_json(JSONfile, orient='columns')

In [39]:
# Writing to a JSON File. orient - values.
JSONfile = './data/target/Book_Values.json'
book_df.to_json(JSONfile, orient='values')

In [40]:
# Writing to a JSON File. orient - table.
JSONfile = './data/target/Book_Table.json'
book_df.to_json(JSONfile, orient='table')

In [48]:
# Reading the JSON file data into a DataFrame.
JSONfile = './data/source/test_data.json'
df = pd.read_json(JSONfile)
df

   userId  id                                              title  completed
0       1   1                                 delectus aut autem      False
1       1   2                 quis ut nam facilis et officia qui      False
2       1   3                                fugiat veniam minus      False
3       1   4                                   et porro tempora       True
4       1   5  laboriosam mollitia et enim quasi adipisci qui...      False

### Reading and Writing Data from HTML File (Web)

In [60]:
# Reading Data from URL.
url = './data/source/wiki.html'
wiki_data = pd.read_html(url)
for table in wiki_data:
    print(table)

    States and union territories of India ordered by
0  Area Population GDP (per capita) Abbreviations...
1                                                vte
         State/Union Territory[a]  2022-23 2023-24  Change
0                   Maharashtra *    36459   40443  10.93%
1                    Tamil Nadu *    23934   27216  13.71%
2                 Uttar Pradesh *    22580   25479  12.84%
3                     Karnataka *    22700   25007  10.16%
4                       Gujarat *    22034   24258  10.09%
5                   West Bengal *    15318   17009  11.04%
6                     Rajasthan *    13579   15284  12.56%
7                     Telangana *    13118   15020   14.5%
8                Andhra Pradesh *    13035   14397  10.44%
9                Madhya Pradesh *    12465   13633   9.37%
10                       Kerala *    10236   11461  11.97%
11                        Delhi *    10147   11077   9.17%
12                      Haryana *     9841   10955  11.33%
13                       Odisha *     7596    8535  12.37%
14                        Bihar *     7464    8544  14.47%
15                       Punjab *     6813    7449   9.34%
16                        Assam *     4788    5702   19.1%
17                 Chhattisgarh *     4644    5059   8.93%
18                    Jharkhand *     4174    4610  10.46%
19                  Uttarakhand *     3038    3462  13.97%
20            Jammu and Kashmir *     2202    2411    9.5%
21             Himachal Pradesh *     1917    2074   8.19%
22                          Goa *      891       —       —
23                      Tripura *      723     826  14.21%
24                   Chandigarh *      550       —       —
25                    Meghalaya *      466     531  13.98%
26                   Puducherry *      447     479   7.16%
27                       Sikkim *      427     489  14.67%
28                      Manipur *      402       —       —
29                     Nagaland *      372       —       —
30            Arunachal Pradesh *      351       —       —
31                      Mizoram *      307       —       —
32  Andaman and Nicobar Islands *      117       —       —
            Zone                           States/Union Territories  \
0       Southern  Andaman and Nicobar, Andhra Pradesh, Karnataka...
1        Western  Dadra and Nagar Haveli and Daman and Diu, Goa,...
2       Northern  Chandigarh, Delhi, Haryana, Himachal Pradesh, ...
3        Central  Chhattisgarh, Madhya Pradesh, Uttarakhand, Utt...
4        Eastern              Bihar, Jharkhand, Odisha, West Bengal
5  North-Eastern  Assam, Arunachal Pradesh, Manipur, Meghalaya, ...
6          India                                                NaN

   GDP (₹ billions) Contribution
0             83587        30.6%
1             59384        21.7%
2             45048        16.5%
3             42727        15.6%
4             34551        12.6%
5              7835         2.9%
6            273133          NaN
            State/Union Territory  2011–12  2012–13  2013–14  2014–15  \
0   Andaman and Nicobar Islands *       40       44       50       55
1                Andhra Pradesh *     3794     4114     4643     5250
2             Arunachal Pradesh *      111      125      146      180
3                         Assam *     1432     1569     1777     1957
4                         Bihar *     2471     2824     3171     3430
5                    Chandigarh *      188      216      248      265
6                  Chhattisgarh *     1581     1775     2068     2211
7                         Delhi *     3438     3914     4440     4948
8                           Goa *      424      381      359      478
9                       Gujarat *     6156     7245     8076     9218
10                      Haryana *     2975     3470     3993     4371
11             Himachal Pradesh *      727      828      948     1038
12            Jammu and Kashmir *      783      871      956      984
13                    Jharkhand *     1509     1747     1886     2185
14                    Karnataka *     6060     6954     8167     9139
15                       Kerala *     3640     4123     4650     5126
16               Madhya Pradesh *     3156     3809     4395     4799
17                  Maharashtra *    12804    14596    16496    17791
18                      Manipur *      129      137      162      181
19                    Meghalaya *      199      219      229      232
20                      Mizoram *       73       84      103      135
21                     Nagaland *      122      141      166      184
22                       Odisha *     2310     2617     2965     3142
23                   Puducherry *      168      189      219      226
24                       Punjab *     2666     2977     3321     3551
25                    Rajasthan *     4348     4936     5510     6156
26                       Sikkim *      112      123      139      154
27                   Tamil Nadu *     7515     8548     9685    10727
28                    Telangana *     3594     4016     4516     5058
29                      Tripura *      192      217      256      295
30                Uttar Pradesh *     7241     8224     9404    10118
31                  Uttarakhand *     1153     1316     1491     1614
32                  West Bengal *     5205     5915     6768     7181

    2015–16  2016–17  2017–18  2018–19  2019–20  2020–21  2021–22  2022–23
0        60       68       79       90       98       93      104      117
1      6042     6844     7861     8737     9258     9786    11485    13035
2       185      199      225      253      300      305      327      351
3      2280     2544     2832     3093     3469     3398     4107     4788
4      3716     4211     4687     5280     5819     5678     6474     7464
5       293      324      363      401      434      394      461      550
6      2252     2628     2827     3271     3447     3523     4105     4644
7      5508     6161     6779     7384     7929     7443     8813    10147
8       551      630      694      719      750      742      812      891
9     10290    11672    13291    14922    16171    16161    19209    22034
10     4955     5614     6388     6989     7381     7291     8689     9841
11     1142     1256     1386     1484     1592     1516     1722     1917
12     1172     1248     1397     1599     1641     1678     1886     2202
13     2066     2362     2698     3057     3103     2967     3761     4174
14    10452    12076    13332    14794    16158    16415    19781    22700
15     5620     6349     7016     7883     8129     7717     9245    10236
16     5411     6498     7263     8298     9279     9466    10930    12465
17    19662    21982    23528    25289    26568    26107    31441    36459
18      195      213      258      274      298      298      350      402
19      251      274      295      322      348      338      402      466
20      151      172      194      219      250      239      267      307
21      195      217      244      265      297      298      323      372
22     3285     3928     4404     4986     5375     5402     6970     7596
23      266      296      321      342      370      362      409      447
24     3901     4270     4710     5125     5370     5409     6277     6813
25     6815     7606     8325     9115    10000    10179    11950    13579
26      180      207      260      284      314      330      376      427
27    11765    13026    14651    16302    17431    17881    20725    23934
28     5779     6583     7501     8574     9501     9431    11241    13118
29      359      395      437      498      542      535      623      723
30    11378    12887    14399    15822    17001    16449    19756    22580
31     1772     1951     2202     2303     2393     2256     2671     3038
32     7973     8725     9747    11021    11791    11418    13292    15318
            State/Union Territory  2012–13  2013–14  2014–15  2015–16  \
0   Andaman and Nicobar Islands *    11.13    13.60     9.05    10.12
1                Andhra Pradesh *     8.43    12.85    13.08    15.10
2             Arunachal Pradesh *    13.41    16.22    23.17     3.06
3                         Assam *     9.56    13.31    10.11    16.47
4                         Bihar *    14.25    12.30     8.15     8.35
5                    Chandigarh *    15.13    14.87     6.96    10.27
6                  Chhattisgarh *    12.30    16.52     6.91     1.83
7                         Delhi *    13.84    13.43    11.45    11.32
8                           Goa *   -10.02    -5.77    33.11    15.14
9                       Gujarat *    17.69    11.47    14.13    11.63
10                      Haryana *    16.63    15.05     9.49    13.35
11             Himachal Pradesh *    13.89    14.42     9.51    10.09
12            Jammu and Kashmir *    11.35     9.74     2.87    19.11
13                    Jharkhand *    15.77     7.92    15.89    -5.45
14                    Karnataka *    14.75    17.44    11.91    14.36
15                       Kerala *    13.26    12.79    10.22     9.64
16               Madhya Pradesh *    20.71    15.37     9.21    12.74
17                  Maharashtra *    14.00    13.02     7.85    10.52
18                      Manipur *     6.42    17.75    12.03     7.73
19                    Meghalaya *     9.81     4.87     1.29     8.10
20                      Mizoram *    15.20    23.10    31.24    12.06
21                     Nagaland *    15.97    17.64    10.77     6.10
22                       Odisha *    13.30    13.29     6.00     4.55
23                   Puducherry *    12.23    15.87     3.22    17.91
24                       Punjab *    11.67    11.56     6.91     9.85
25                    Rajasthan *    13.50    11.65    11.73    10.69
26                       Sikkim *    10.51    12.35    11.14    17.05
27                   Tamil Nadu *    13.75    13.30    10.75     9.68
28                    Telangana *    11.73    12.45    12.02    14.24
29                      Tripura *    12.78    18.14    15.40    21.68
30                Uttar Pradesh *    13.58    14.34     7.60    12.45
31                  Uttarakhand *    14.12    13.27     8.29     9.74
32                  West Bengal *    13.64    14.44     6.09    11.03

    2016–17  2017–18  2018–19  2019–20  2020–21  2021–22  2022–23
0     13.33    15.43    14.10     8.46    -4.66    11.62    12.29
1     13.27    14.86    11.14     5.97     5.70    17.36    13.50
2      7.53    12.93    12.73    18.51     1.67     7.14     7.34
3     11.59    11.31     9.24    12.13    -2.03    20.87    16.57
4     13.31    11.33    12.64    10.20    -2.41    14.02    15.30
5     10.77    12.08    10.44     8.18    -9.23    16.84    19.41
6     16.72     7.59    15.69     5.37     2.22    16.52    13.12
7     11.85    10.03     8.92     7.38    -6.13    18.41    15.13
8     14.39    10.12     3.61     4.42    -1.17     9.53     9.73
9     13.43    13.87    12.27     8.38    -0.06    18.86    14.71
10    13.30    13.79     9.41     5.60    -1.22    19.18    13.25
11     9.97    10.28     7.10     7.27    -4.75    13.56    11.36
12     6.55    11.90    14.42     2.65     2.25    12.38    16.78
13    14.34    14.21    13.30     1.51    -4.40    26.79    10.96
14    15.54    10.40    10.96     9.22     1.59    20.51    14.76
15    12.97    10.51    12.36     3.13    -5.07    19.79    10.72
16    20.10    11.77    14.25    11.82     2.02    15.46    14.05
17    11.80     7.03     7.48     5.06    -1.74    20.44    15.96
18     9.03    21.11     6.20     8.85    -0.12    17.64    14.89
19     9.24     7.54     9.04     8.06    -2.86    19.08    15.74
20    13.56    12.76    13.03    14.04    -4.27    11.59    14.97
21    11.26    12.29     8.75    12.02     0.39     8.16    15.14
22    19.56    12.12    13.22     7.80     0.50    29.03     8.97
23    11.11     8.64     6.36     8.28    -2.21    13.06     9.28
24     9.46    10.31     8.81     4.78     0.71    16.06     8.53
25    11.61     9.46     9.49     9.71     1.79    17.39    13.63
26    14.71    25.54     9.36    10.70     5.02    14.03    13.35
27    10.72    12.47    11.27     6.93     2.58    15.91    15.48
28    13.92    13.93    14.32    10.81    -0.74    19.19    16.70
29     9.86    10.73    13.97     8.69    -1.19    16.44    16.12
30    13.26    11.73     9.88     7.45    -3.24    20.10    14.30
31    10.14    12.86     4.59     3.88    -5.70    18.41    13.71
32     9.44    11.71    13.07     6.99    -3.17    16.42    15.24
  showvteList of Asian subdivisions by GDP  \
0                         Sovereign states
1          States with limited recognition

          showvteList of Asian subdivisions by GDP.1
0  Afghanistan Armenia Azerbaijan Bahrain Banglad...
1  Abkhazia Northern Cyprus Palestine South Osset...
           showvteLists of countries by GDP rankings  \
0                                            Nominal
1                      Purchasing power parity (PPP)
2                                         Per capita
3                                    Economic growth
4                                       Productivity
5                        Gross national income (GNI)
6                                Countries by region
7                              Subnational divisions
8  Lists of countries by financial rankings List ...

         showvteLists of countries by GDP rankings.1
0  GDP (nominal) Past and projected Sector compos...
1  GDP (PPP) Past Past and projected Ten largest ...
2  nominal GDP Past and projected GDP (PPP) by re...
3  real GDP growth rate African countries Asian s...
4                                Labour productivity
5  PPP per capita Nominal per capita Real income ...
6  Africa PPP nominal Arab League nominal and per...
7  Albania Argentina Armenia ASEAN Australia citi...
8  Lists of countries by financial rankings List ...

In [62]:
gdp_df = wiki_data[1]
gdp_df.head()

  State/Union Territory[a]  2022-23 2023-24  Change
0            Maharashtra *    36459   40443  10.93%
1             Tamil Nadu *    23934   27216  13.71%
2          Uttar Pradesh *    22580   25479  12.84%
3              Karnataka *    22700   25007  10.16%
4                Gujarat *    22034   24258  10.09%

In [64]:
# Writing to HTML File.
tgtfile = './data/target/india_gdp.html'
gdp_df.to_html(tgtfile)